name: intranet-news-platform

include:
  - ./backend-java/docker/docker-compose-single-db.yml

services:
  frontend:
    image: intranet-news-platform-frontend
    build: ./frontend
    ports:
      - "4200:80"