server:
  port: 8086
  forward-headers-strategy: native

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "localhost"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

      discovery:
        locator:
          enabled: true

      routes:
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/post/**

        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/review/**

springdoc:
  swagger-ui:
    use-root-path: true
    urls:
      - name: post
        url: /post/v3/api-docs

      - name: review
        url: /review/v3/api-docs
  webjars:
    prefix: ""
  cache:
    disabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
