server:
  port: 8086

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "localhost"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

      discovery:
        locator:
          enabled: true

      routes:
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/post/**
          filters:
            - RewritePath=/post/(?<path>.*), /$\{path}

        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/review/**
          filters:
            - RewritePath=/review/(?<path>.*), /$\{path}

        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/api/v3/api-docs

springdoc:
  swagger-ui:
    use-root-path: true
    urls:
      - name: post
        url: /v3/api-docs/post/

      - name: review
        url: /v3/api-docs/review/
  webjars:
    prefix: ""
  cache:
    disabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
